# Generated by Django 3.1 on 2020-09-24 22:14

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('dni', models.IntegerField(blank=True, null=True)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d')),
                ('phone', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numero', models.IntegerField(blank=True)),
                ('piso', models.CharField(blank=True, max_length=25)),
                ('altura', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoSanguineo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('num_poliza', models.IntegerField()),
                ('tel', models.IntegerField()),
                ('tel_emergencia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoCarnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uso', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=45)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.marca')),
                ('tipo_v', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='user.tipovehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Cedula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cedula', models.CharField(max_length=45)),
                ('patente', models.CharField(max_length=15)),
                ('num_motor', models.IntegerField()),
                ('num_chasis', models.IntegerField()),
                ('emision', models.DateField()),
                ('vencimiento', models.DateField()),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.modelo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('uso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.tipouso')),
            ],
        ),
        migrations.CreateModel(
            name='Carnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_carnet', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('otorgamiento', models.DateField()),
                ('vencimiento', models.DateField()),
                ('donante', models.BooleanField(default=False)),
                ('validado', models.BooleanField(blank=True, default=False)),
                ('grupo_s', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.gruposanguineo')),
                ('tipo_carnet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.tipocarnet')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.direcciones'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nacionalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.nacionalidad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
