# Generated by Django 3.1 on 2020-09-15 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarnet', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='AppCarnet.direcciones'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='grupo_s',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='AppCarnet.gruposanguineo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='AppCarnet.nacionalidad'),
        ),
    ]
