# Generated by Django 3.1 on 2020-09-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200918_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='validado',
        ),
    ]
