# Generated by Django 3.1 on 2020-09-22 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarnet', '0010_auto_20200922_1125'),
        ('user', '0003_remove_usuario_validado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='donante',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='grupo_s',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCarnet.direcciones'),
        ),
    ]
