# Generated by Django 3.1.1 on 2020-09-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200929_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnet',
            name='slug',
            field=models.SlugField(default='fix-me'),
            preserve_default=False,
        ),
    ]
