# Generated by Django 3.1 on 2020-09-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_nacionalidad_cantidad_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nacionalidad',
            name='cantidad_users',
        ),
    ]
