# Generated by Django 3.1.1 on 2020-09-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_carnet_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carnet',
            name='slug',
        ),
    ]
