# Generated by Django 3.1 on 2020-09-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_usuario_validado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='validado',
            field=models.BooleanField(default=False),
        ),
    ]
