# Generated by Django 3.1 on 2020-09-30 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_carnet_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carnet',
            name='foto',
        ),
    ]
