# Generated by Django 3.1 on 2020-09-28 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200928_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nacionalidad',
            old_name='cantidad_users',
            new_name='cantidad_carnet',
        ),
    ]
