# Generated by Django 3.1.1 on 2020-09-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200928_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carnet',
            name='foto',
        ),
        migrations.AddField(
            model_name='carnet',
            name='foto_atras',
            field=models.ImageField(blank=True, null=True, upload_to='media/carnet/atras/'),
        ),
        migrations.AddField(
            model_name='carnet',
            name='foto_frente',
            field=models.ImageField(blank=True, null=True, upload_to='media/carnet/frente/'),
        ),
        migrations.AddField(
            model_name='cedula',
            name='foto_atras',
            field=models.ImageField(blank=True, null=True, upload_to='media/cedula/atras/'),
        ),
        migrations.AddField(
            model_name='cedula',
            name='foto_frente',
            field=models.ImageField(blank=True, null=True, upload_to='media/cedula/frente/'),
        ),
    ]
