# Generated by Django 3.1 on 2020-10-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200928_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carnet',
            name='foto_atras',
        ),
        migrations.RemoveField(
            model_name='cedula',
            name='foto_atras',
        ),
    ]
