# Generated by Django 3.1.1 on 2020-10-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20201001_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnet',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/carnet/user/'),
        ),
    ]
