# Generated by Django 3.1.1 on 2020-10-01 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_carnet_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='image',
        ),
    ]
