# Generated by Django 3.1 on 2020-09-18 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('piso', models.CharField(max_length=25)),
                ('altura', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoSanguineo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('num_poliza', models.IntegerField()),
                ('tel', models.IntegerField()),
                ('tel_emergencia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoCarnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uso', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=45)),
                ('anio', models.DateField()),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppCarnet.marca')),
                ('tipo_v', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='AppCarnet.tipovehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Cedula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cedula', models.CharField(max_length=45)),
                ('patente', models.CharField(max_length=15)),
                ('num_motor', models.IntegerField()),
                ('num_chasis', models.IntegerField()),
                ('emision', models.DateField()),
                ('vencimiento', models.DateField()),
                ('seguro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppCarnet.seguro')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppCarnet.tipovehiculo')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppCarnet.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Carnet',
            fields=[
                ('n_carnet', models.IntegerField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_persona')),
                ('otorgamiento', models.DateField()),
                ('vencimiento', models.DateField()),
                ('donante', models.BooleanField(default=False)),
                ('validado', models.BooleanField(blank=True, default=False)),
                ('grupo_s', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='AppCarnet.gruposanguineo')),
                ('tipo_carnet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='AppCarnet.tipocarnet')),
            ],
        ),
    ]
