# Generated by Django 3.1 on 2020-09-21 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarnet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cedula',
            old_name='vehiculo',
            new_name='modelo',
        ),
        migrations.AddField(
            model_name='cedula',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCarnet.marca'),
        ),
        migrations.AddField(
            model_name='cedula',
            name='uso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCarnet.tipouso'),
        ),
    ]
