# Generated by Django 3.1 on 2020-09-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarnet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnet',
            name='n_carnet',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='carnet',
            name='validado',
            field=models.BooleanField(default=False),
        ),
    ]
