# Generated by Django 3.0.7 on 2020-09-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarnet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
