# Generated by Django 3.1 on 2020-09-14 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarnet', '0002_auto_20200914_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='donante',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='grupo_s',
        ),
        migrations.AddField(
            model_name='carnet',
            name='donante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carnet',
            name='grupo_s',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='AppCarnet.gruposanguineo'),
        ),
        migrations.AlterField(
            model_name='direcciones',
            name='altura',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCarnet.direcciones'),
        ),
    ]
