# Generated by Django 3.1 on 2020-09-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarnet', '0003_remove_modelo_anio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cedula',
            name='tipo',
        ),
    ]
