# Generated by Django 3.1 on 2020-09-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarnet', '0003_auto_20200917_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carnet',
            name='id',
        ),
        migrations.AlterField(
            model_name='carnet',
            name='n_carnet',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
