# Generated by Django 3.1 on 2020-09-14 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarnet', '0004_auto_20200914_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AppCarnet.nacionalidad'),
        ),
    ]
