# Generated by Django 3.1 on 2020-09-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarnet', '0005_auto_20200914_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nacionalidad',
            name='id',
        ),
        migrations.AlterField(
            model_name='nacionalidad',
            name='nacionalidad',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
