# Generated by Django 3.1 on 2020-09-17 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarnet', '0005_auto_20200917_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnet',
            name='grupo_s',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AppCarnet.gruposanguineo'),
        ),
        migrations.AlterField(
            model_name='carnet',
            name='tipo_carnet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AppCarnet.tipocarnet'),
        ),
    ]
