# Generated by Django 3.1.1 on 2020-09-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarnet', '0006_auto_20200921_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnet',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='ProyectoCarnet\\ProyectoCarnet\\AppCarnet\\static\\media\x0cotos_persona'),
        ),
    ]
