# Generated by Django 3.1 on 2020-09-14 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarnet', '0006_auto_20200914_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='nacionalidad',
        ),
        migrations.DeleteModel(
            name='Nacionalidad',
        ),
    ]
