# Generated by Django 3.1 on 2020-09-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarnet', '0008_auto_20200917_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocarnet',
            name='tipo',
            field=models.CharField(max_length=5),
        ),
    ]
