# Generated by Django 3.1 on 2020-09-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarnet', '0009_auto_20200921_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direcciones',
            name='numero',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='direcciones',
            name='piso',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
