# Generated by Django 3.1.1 on 2020-09-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarnet', '0009_auto_20200921_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnet',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/fotos_persona/'),
        ),
    ]
