# Generated by Django 3.1 on 2020-09-17 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarnet', '0010_auto_20200917_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uso', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='año',
            new_name='anio',
        ),
        migrations.RemoveField(
            model_name='cedula',
            name='nombre_registro',
        ),
        migrations.RemoveField(
            model_name='seguro',
            name='tipo',
        ),
        migrations.AddField(
            model_name='modelo',
            name='tipo_v',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='AppCarnet.tipovehiculo'),
        ),
        migrations.DeleteModel(
            name='TipoSeguro',
        ),
    ]
